version: '3.3'
services:
  db:
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'America/Sao_Paulo'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ~/.MySQLDBData/mysqlonly/mysql_knex/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "npm run migrate && npm run dev"
volumes:
  my-db: