version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'America/Sao_Paulo'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  app:
    image: node:18-alpine
    container_name: app-container
    working_dir: /app
    command: sh -c "npm i && npm run migrate && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: db

volumes:
  my-db:
